kvm: Initialize kvm_physical_log_clear ret local variable
If there is no slot in the section ret is not initialized. This triggers
a compilation error at caller site.

error: ‘ret’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
     if (r < 0) {

Fixes: 84516e5b8d ("kvm: clear dirty bitmaps from all overlapping memslots")
Signed-off-by: Eric Auger <eric.auger@redhat.com>