target/arm/cpu_idregs: generate tables for Arm64 ID registers and fields
Include cpu-idregs.h.inc multiple times with different definitions for the
X-macros. This will generate tables for all Arm64 ID registers and their
fields. Additionally, initialize the tables with all architecturally defined
values. These tables will be consumed by the property layer in future
patches.

Note:
This triggers a minot checkpatch error but I prefer to keep the coma in
the macro.
ERROR: Macros with complex values should be enclosed in parenthesis
+#define IDREG_FIELD_ARCH_VAL(v) (v),

Co-authored-by: Khushit Shah <khushit.shah@nutanix.com>
Signed-off-by: Khushit Shah <khushit.shah@nutanix.com>
Signed-off-by: Shaju Abraham <shaju.abraham@nutanix.com>
Signed-off-by: Eric Auger <eric.auger@redhat.com>

---
v7 -> v8
Adaptation after removal of struct ArmIdRegArchVal

v5 -> v6
- restored support of enum values